// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package fsm

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSnapshotDB creates a new instance of MockSnapshotDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnapshotDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnapshotDB {
	mock := &MockSnapshotDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSnapshotDB is an autogenerated mock type for the SnapshotDB type
type MockSnapshotDB struct {
	mock.Mock
}

type MockSnapshotDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnapshotDB) EXPECT() *MockSnapshotDB_Expecter {
	return &MockSnapshotDB_Expecter{mock: &_m.Mock}
}

// Backup provides a mock function for the type MockSnapshotDB
func (_mock *MockSnapshotDB) Backup(w io.Writer, since uint64) (uint64, error) {
	ret := _mock.Called(w, since)

	if len(ret) == 0 {
		panic("no return value specified for Backup")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(io.Writer, uint64) (uint64, error)); ok {
		return returnFunc(w, since)
	}
	if returnFunc, ok := ret.Get(0).(func(io.Writer, uint64) uint64); ok {
		r0 = returnFunc(w, since)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(io.Writer, uint64) error); ok {
		r1 = returnFunc(w, since)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnapshotDB_Backup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Backup'
type MockSnapshotDB_Backup_Call struct {
	*mock.Call
}

// Backup is a helper method to define mock.On call
//   - w io.Writer
//   - since uint64
func (_e *MockSnapshotDB_Expecter) Backup(w interface{}, since interface{}) *MockSnapshotDB_Backup_Call {
	return &MockSnapshotDB_Backup_Call{Call: _e.mock.On("Backup", w, since)}
}

func (_c *MockSnapshotDB_Backup_Call) Run(run func(w io.Writer, since uint64)) *MockSnapshotDB_Backup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Writer
		if args[0] != nil {
			arg0 = args[0].(io.Writer)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSnapshotDB_Backup_Call) Return(v uint64, err error) *MockSnapshotDB_Backup_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockSnapshotDB_Backup_Call) RunAndReturn(run func(w io.Writer, since uint64) (uint64, error)) *MockSnapshotDB_Backup_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockSnapshotDB
func (_mock *MockSnapshotDB) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSnapshotDB_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSnapshotDB_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockSnapshotDB_Expecter) Close() *MockSnapshotDB_Close_Call {
	return &MockSnapshotDB_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockSnapshotDB_Close_Call) Run(run func()) *MockSnapshotDB_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSnapshotDB_Close_Call) Return(err error) *MockSnapshotDB_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSnapshotDB_Close_Call) RunAndReturn(run func() error) *MockSnapshotDB_Close_Call {
	_c.Call.Return(run)
	return _c
}
