// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kayak

import (
	"time"

	"github.com/hashicorp/raft"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRaftInterface creates a new instance of MockRaftInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRaftInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRaftInterface {
	mock := &MockRaftInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRaftInterface is an autogenerated mock type for the RaftInterface type
type MockRaftInterface struct {
	mock.Mock
}

type MockRaftInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRaftInterface) EXPECT() *MockRaftInterface_Expecter {
	return &MockRaftInterface_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockRaftInterface
func (_mock *MockRaftInterface) Apply(cmd []byte, timeout time.Duration) raft.ApplyFuture {
	ret := _mock.Called(cmd, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 raft.ApplyFuture
	if returnFunc, ok := ret.Get(0).(func([]byte, time.Duration) raft.ApplyFuture); ok {
		r0 = returnFunc(cmd, timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(raft.ApplyFuture)
		}
	}
	return r0
}

// MockRaftInterface_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockRaftInterface_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - cmd
//   - timeout
func (_e *MockRaftInterface_Expecter) Apply(cmd interface{}, timeout interface{}) *MockRaftInterface_Apply_Call {
	return &MockRaftInterface_Apply_Call{Call: _e.mock.On("Apply", cmd, timeout)}
}

func (_c *MockRaftInterface_Apply_Call) Run(run func(cmd []byte, timeout time.Duration)) *MockRaftInterface_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockRaftInterface_Apply_Call) Return(applyFuture raft.ApplyFuture) *MockRaftInterface_Apply_Call {
	_c.Call.Return(applyFuture)
	return _c
}

func (_c *MockRaftInterface_Apply_Call) RunAndReturn(run func(cmd []byte, timeout time.Duration) raft.ApplyFuture) *MockRaftInterface_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Leader provides a mock function for the type MockRaftInterface
func (_mock *MockRaftInterface) Leader() raft.ServerAddress {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Leader")
	}

	var r0 raft.ServerAddress
	if returnFunc, ok := ret.Get(0).(func() raft.ServerAddress); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(raft.ServerAddress)
	}
	return r0
}

// MockRaftInterface_Leader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Leader'
type MockRaftInterface_Leader_Call struct {
	*mock.Call
}

// Leader is a helper method to define mock.On call
func (_e *MockRaftInterface_Expecter) Leader() *MockRaftInterface_Leader_Call {
	return &MockRaftInterface_Leader_Call{Call: _e.mock.On("Leader")}
}

func (_c *MockRaftInterface_Leader_Call) Run(run func()) *MockRaftInterface_Leader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRaftInterface_Leader_Call) Return(serverAddress raft.ServerAddress) *MockRaftInterface_Leader_Call {
	_c.Call.Return(serverAddress)
	return _c
}

func (_c *MockRaftInterface_Leader_Call) RunAndReturn(run func() raft.ServerAddress) *MockRaftInterface_Leader_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function for the type MockRaftInterface
func (_mock *MockRaftInterface) State() raft.RaftState {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 raft.RaftState
	if returnFunc, ok := ret.Get(0).(func() raft.RaftState); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(raft.RaftState)
	}
	return r0
}

// MockRaftInterface_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type MockRaftInterface_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
func (_e *MockRaftInterface_Expecter) State() *MockRaftInterface_State_Call {
	return &MockRaftInterface_State_Call{Call: _e.mock.On("State")}
}

func (_c *MockRaftInterface_State_Call) Run(run func()) *MockRaftInterface_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRaftInterface_State_Call) Return(raftState raft.RaftState) *MockRaftInterface_State_Call {
	_c.Call.Return(raftState)
	return _c
}

func (_c *MockRaftInterface_State_Call) RunAndReturn(run func() raft.RaftState) *MockRaftInterface_State_Call {
	_c.Call.Return(run)
	return _c
}
