openapi: 3.1.0
info:
  title: kayak.v1
paths:
  /kayak.v1.AdminService/AddVoter:
    post:
      tags:
        - kayak.v1.AdminService
      summary: AddVoter
      operationId: kayak.v1.AdminService.AddVoter
      parameters:
        - name: Connect-Protocol-Version
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/connect-protocol-version'
        - name: Connect-Timeout-Ms
          in: header
          schema:
            $ref: '#/components/schemas/connect-timeout-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/kayak.v1.AddVoterRequest'
        required: true
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.error'
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/kayak.v1.AddVoterResponse'
  /kayak.v1.AdminService/Stats:
    post:
      tags:
        - kayak.v1.AdminService
      summary: Stats
      operationId: kayak.v1.AdminService.Stats
      parameters:
        - name: Connect-Protocol-Version
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/connect-protocol-version'
        - name: Connect-Timeout-Ms
          in: header
          schema:
            $ref: '#/components/schemas/connect-timeout-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/kayak.v1.StatsRequest'
        required: true
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.error'
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/kayak.v1.StatsResponse'
  /kayak.v1.AdminService/Leader:
    post:
      tags:
        - kayak.v1.AdminService
      summary: Leader
      operationId: kayak.v1.AdminService.Leader
      parameters:
        - name: Connect-Protocol-Version
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/connect-protocol-version'
        - name: Connect-Timeout-Ms
          in: header
          schema:
            $ref: '#/components/schemas/connect-timeout-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/kayak.v1.LeaderRequest'
        required: true
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.error'
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/kayak.v1.LeaderResponse'
components:
  schemas:
    kayak.v1.AddVoterRequest:
      type: object
      properties:
        id:
          type: string
          title: id
        address:
          type: string
          title: address
      title: AddVoterRequest
      additionalProperties: false
    kayak.v1.AddVoterResponse:
      type: object
      title: AddVoterResponse
      additionalProperties: false
    kayak.v1.ConfigItem:
      type: object
      properties:
        suffrage:
          type: string
          title: suffrage
        id:
          type: string
          title: id
        address:
          type: string
          title: address
      title: ConfigItem
      additionalProperties: false
    kayak.v1.LeaderRequest:
      type: object
      title: LeaderRequest
      additionalProperties: false
    kayak.v1.LeaderResponse:
      type: object
      properties:
        address:
          type: string
          title: address
        id:
          type: string
          title: id
      title: LeaderResponse
      additionalProperties: false
    kayak.v1.StatsRequest:
      type: object
      title: StatsRequest
      additionalProperties: false
    kayak.v1.StatsResponse:
      type: object
      properties:
        state:
          type: string
          title: state
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/kayak.v1.ConfigItem'
          title: nodes
        term:
          type: string
          title: term
        fsmPending:
          type: string
          title: fsm_pending
          description: map<string, string> stats = 1;
      title: StatsResponse
      additionalProperties: false
    connect-protocol-version:
      type: number
      title: Connect-Protocol-Version
      enum:
        - 1
      description: Define the version of the Connect protocol
      const: 1
    connect-timeout-header:
      type: number
      title: Connect-Timeout-Ms
      description: Define the timeout, in ms
    connect.error:
      type: object
      properties:
        code:
          type: string
          examples:
            - not_found
          enum:
            - canceled
            - unknown
            - invalid_argument
            - deadline_exceeded
            - not_found
            - already_exists
            - permission_denied
            - resource_exhausted
            - failed_precondition
            - aborted
            - out_of_range
            - unimplemented
            - internal
            - unavailable
            - data_loss
            - unauthenticated
          description: The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
        message:
          type: string
          description: A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
        detail:
          $ref: '#/components/schemas/google.protobuf.Any'
      title: Connect Error
      additionalProperties: true
      description: 'Error type returned by Connect: https://connectrpc.com/docs/go/errors/#http-representation'
    google.protobuf.Any:
      type: object
      properties:
        type:
          type: string
        value:
          type: string
          format: binary
        debug:
          type: object
          additionalProperties: true
      additionalProperties: true
      description: Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
security: []
tags:
  - name: kayak.v1.AdminService
