openapi: 3.1.0
info:
  title: kayak.v1
paths: {}
components:
  schemas:
    kayak.v1.Operation:
      type: string
      title: Operation
      enum:
        - OPERATION_UNSPECIFIED
        - OPERATION_PUT_STREAM
        - OPERATION_PUT_RECORDS
        - OPERATION_EXTEND_LEASE
        - OPERATION_REMOVE_LEASE
        - OPERATION_COMMIT_GROUP_POSITION
    google.protobuf.Timestamp:
      type: string
      format: date-time
      description: |-
        A Timestamp represents a point in time independent of any time zone or local
         calendar, encoded as a count of seconds and fractions of seconds at
         nanosecond resolution. The count is relative to an epoch at UTC midnight on
         January 1, 1970, in the proleptic Gregorian calendar which extends the
         Gregorian calendar backwards to year one.

         All minutes are 60 seconds long. Leap seconds are "smeared" so that no leap
         second table is needed for interpretation, using a [24-hour linear
         smear](https://developers.google.com/time/smear).

         The range is from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59.999999999Z. By
         restricting to that range, we ensure that we can convert to and from [RFC
         3339](https://www.ietf.org/rfc/rfc3339.txt) date strings.

         # Examples

         Example 1: Compute Timestamp from POSIX `time()`.

             Timestamp timestamp;
             timestamp.set_seconds(time(NULL));
             timestamp.set_nanos(0);

         Example 2: Compute Timestamp from POSIX `gettimeofday()`.

             struct timeval tv;
             gettimeofday(&tv, NULL);

             Timestamp timestamp;
             timestamp.set_seconds(tv.tv_sec);
             timestamp.set_nanos(tv.tv_usec * 1000);

         Example 3: Compute Timestamp from Win32 `GetSystemTimeAsFileTime()`.

             FILETIME ft;
             GetSystemTimeAsFileTime(&ft);
             UINT64 ticks = (((UINT64)ft.dwHighDateTime) << 32) | ft.dwLowDateTime;

             // A Windows tick is 100 nanoseconds. Windows epoch 1601-01-01T00:00:00Z
             // is 11644473600 seconds before Unix epoch 1970-01-01T00:00:00Z.
             Timestamp timestamp;
             timestamp.set_seconds((INT64) ((ticks / 10000000) - 11644473600LL));
             timestamp.set_nanos((INT32) ((ticks % 10000000) * 100));

         Example 4: Compute Timestamp from Java `System.currentTimeMillis()`.

             long millis = System.currentTimeMillis();

             Timestamp timestamp = Timestamp.newBuilder().setSeconds(millis / 1000)
                 .setNanos((int) ((millis % 1000) * 1000000)).build();

         Example 5: Compute Timestamp from Java `Instant.now()`.

             Instant now = Instant.now();

             Timestamp timestamp =
                 Timestamp.newBuilder().setSeconds(now.getEpochSecond())
                     .setNanos(now.getNano()).build();

         Example 6: Compute Timestamp from current time in Python.

             timestamp = Timestamp()
             timestamp.GetCurrentTime()

         # JSON Mapping

         In JSON format, the Timestamp type is encoded as a string in the
         [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format. That is, the
         format is "{year}-{month}-{day}T{hour}:{min}:{sec}[.{frac_sec}]Z"
         where {year} is always expressed using four digits while {month}, {day},
         {hour}, {min}, and {sec} are zero-padded to two digits each. The fractional
         seconds, which can go up to 9 digits (i.e. up to 1 nanosecond resolution),
         are optional. The "Z" suffix indicates the timezone ("UTC"); the timezone
         is required. A proto3 JSON serializer should always use UTC (as indicated by
         "Z") when printing the Timestamp type and a proto3 JSON parser should be
         able to accept both UTC and other timezones (as indicated by an offset).

         For example, "2017-01-15T01:30:15.01Z" encodes 15.01 seconds past
         01:30 UTC on January 15, 2017.

         In JavaScript, one can convert a Date object to this format using the
         standard
         [toISOString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString)
         method. In Python, a standard `datetime.datetime` object can be converted
         to this format using
         [`strftime`](https://docs.python.org/2/library/time.html#time.strftime) with
         the time format spec '%Y-%m-%dT%H:%M:%S.%fZ'. Likewise, in Java, one can use
         the Joda Time's [`ISODateTimeFormat.dateTime()`](
         http://joda-time.sourceforge.net/apidocs/org/joda/time/format/ISODateTimeFormat.html#dateTime()
         ) to obtain a formatter capable of generating timestamps in this format.
    kayak.v1.CommitGroupPosition:
      type: object
      properties:
        streamName:
          type: string
          title: stream_name
        groupName:
          type: string
          title: group_name
        partition:
          type:
            - integer
            - string
          title: partition
          format: int64
        position:
          type: string
          title: position
      title: CommitGroupPosition
      additionalProperties: false
    kayak.v1.DeleteStream:
      type: object
      properties:
        streamName:
          type: string
          title: stream_name
      title: DeleteStream
      additionalProperties: false
    kayak.v1.ExtendLease:
      type: object
      properties:
        worker:
          title: worker
          $ref: '#/components/schemas/kayak.v1.Worker'
        expiresMs:
          type:
            - integer
            - string
          title: expires_ms
          format: int64
      title: ExtendLease
      additionalProperties: false
    kayak.v1.Group:
      type: object
      properties:
        streamName:
          type: string
          title: stream_name
        name:
          type: string
          title: name
        partitionPositions:
          type: object
          title: partition_positions
          additionalProperties:
            type: string
            title: value
      title: Group
      additionalProperties: false
    kayak.v1.Group.PartitionPositionsEntry:
      type: object
      properties:
        key:
          type:
            - integer
            - string
          title: key
          format: int64
        value:
          type: string
          title: value
      title: PartitionPositionsEntry
      additionalProperties: false
    kayak.v1.PutRecords:
      type: object
      properties:
        streamName:
          type: string
          title: stream_name
        records:
          type: array
          items:
            $ref: '#/components/schemas/kayak.v1.Record'
          title: records
      title: PutRecords
      additionalProperties: false
    kayak.v1.PutStream:
      type: object
      properties:
        stream:
          title: stream
          $ref: '#/components/schemas/kayak.v1.Stream'
      title: PutStream
      additionalProperties: false
    kayak.v1.RaftCommand:
      type: object
      oneOf:
        - properties:
            commitGroupPosition:
              title: commit_group_position
              $ref: '#/components/schemas/kayak.v1.CommitGroupPosition'
          title: commit_group_position
          required:
            - commitGroupPosition
        - properties:
            deleteStream:
              title: delete_stream
              $ref: '#/components/schemas/kayak.v1.DeleteStream'
          title: delete_stream
          required:
            - deleteStream
        - properties:
            extendLease:
              title: extend_lease
              $ref: '#/components/schemas/kayak.v1.ExtendLease'
          title: extend_lease
          required:
            - extendLease
        - properties:
            putRecords:
              title: put_records
              $ref: '#/components/schemas/kayak.v1.PutRecords'
          title: put_records
          required:
            - putRecords
        - properties:
            putStream:
              title: put_stream
              $ref: '#/components/schemas/kayak.v1.PutStream'
          title: put_stream
          required:
            - putStream
        - properties:
            removeLease:
              title: remove_lease
              $ref: '#/components/schemas/kayak.v1.RemoveLease'
          title: remove_lease
          required:
            - removeLease
      properties:
        operation:
          title: operation
          $ref: '#/components/schemas/kayak.v1.Operation'
      title: RaftCommand
      additionalProperties: false
    kayak.v1.Record:
      type: object
      properties:
        streamName:
          type: string
          title: stream_name
          description: name of the stream the record is being added to. Will be set by PutRecordsRequest
        partition:
          type:
            - integer
            - string
          title: partition
          format: int64
          description: partition is set by server.
        id:
          type: string
          title: id
          description: id is used to hashed and used for partition assignment, can be set by client.
        internalId:
          type: string
          title: internal_id
          description: internal id is used as identifier in partition stream. Set by server.
        headers:
          type: object
          title: headers
          additionalProperties:
            type: string
            title: value
        payload:
          type: string
          title: payload
          format: byte
        acceptTimestamp:
          title: accept_timestamp
          $ref: '#/components/schemas/google.protobuf.Timestamp'
      title: Record
      required:
        - payload
      additionalProperties: false
    kayak.v1.Record.HeadersEntry:
      type: object
      properties:
        key:
          type: string
          title: key
        value:
          type: string
          title: value
      title: HeadersEntry
      additionalProperties: false
    kayak.v1.RemoveLease:
      type: object
      properties:
        worker:
          title: worker
          $ref: '#/components/schemas/kayak.v1.Worker'
      title: RemoveLease
      additionalProperties: false
    kayak.v1.Stream:
      type: object
      properties:
        name:
          type: string
          title: name
        partitionCount:
          type:
            - integer
            - string
          title: partition_count
          format: int64
        ttl:
          type:
            - integer
            - string
          title: ttl
          format: int64
        stats:
          title: stats
          nullable: true
          $ref: '#/components/schemas/kayak.v1.StreamStats'
      title: Stream
      additionalProperties: false
    kayak.v1.StreamStats:
      type: object
      properties:
        partitionCounts:
          type: object
          title: partition_counts
          additionalProperties:
            type:
              - integer
              - string
            title: value
            format: int64
        recordCount:
          type:
            - integer
            - string
          title: record_count
          format: int64
        groups:
          type: array
          items:
            $ref: '#/components/schemas/kayak.v1.Group'
          title: groups
      title: StreamStats
      additionalProperties: false
    kayak.v1.StreamStats.PartitionCountsEntry:
      type: object
      properties:
        key:
          type:
            - integer
            - string
          title: key
          format: int64
        value:
          type:
            - integer
            - string
          title: value
          format: int64
      title: PartitionCountsEntry
      additionalProperties: false
    kayak.v1.Worker:
      type: object
      properties:
        streamName:
          type: string
          title: stream_name
        groupName:
          type: string
          title: group_name
        id:
          type: string
          title: id
        partitionAssignment:
          type:
            - integer
            - string
          title: partition_assignment
          format: int64
        position:
          type: string
          title: position
        leaseExpires:
          type:
            - integer
            - string
          title: lease_expires
          format: int64
      title: Worker
      additionalProperties: false
security: []
