syntax = "proto3";

package kayak.v1;

import "buf/validate/validate.proto";
import "kayak/v1/model.proto";

option go_package = "github.com/binarymatt/kayak/gen/kayak/v1;kayakv1";

message RaftCommand {
  oneof payload {
    PutStreamRequest put_stream = 2;
    PutRecordsRequest put_records = 3;
    ExtendLease extend_lease = 4;
    RemoveLease remove_lease = 5;
    CommitGroupPosition commit_group_position = 6;
    DeleteStreamRequest delete_stream = 7;
    DeleteRecordsRequest delete_records = 8;
  }
}

message DeleteStreamRequest {
  string name = 1 [(buf.validate.field).required = true];
}
message PutStreamRequest {
  Stream stream = 1;
}
message PutRecordsRequest {
  string stream_name = 1;
  repeated Record records = 2;
  string idempotency_key = 3;
}
message ExtendLease {
  Worker worker = 1;
  int64 expires_ms = 2;
}
message RemoveLease {
  Worker worker = 1;
}
message CommitGroupPosition {
  string stream_name = 1;
  string group_name = 2;
  int64 partition = 3;
  string position = 4;
}

message DeleteRecordsRequest {
  string name = 1 [(buf.validate.field).required = true];
  int64 partition = 2;
}
